# Generated by Django 5.0.3 on 2024-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_profile_options_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='\\Documents\\Actual_Python\\DJANGO_PET_PROJ\\website-with-blogs\\static\\img\\default-profile-pic.jpg', null=True, upload_to='profile/'),
        ),
    ]
